vivienda <- read.csv("C:/Users/rjds_/Downloads/TRVIVIENDA02.csv", header=FALSE)
names(vivienda)
head(vivienda)
levels(vivienda$V5)
nrow(vivienda)
ncol(vivienda)
sort(vivienda$V5)
length(vivienda$V5)
which(vivienda$V5=='Tijuana')
length(which(vivenda$V5=='Mexicali'))
table(vivenda$V5)
prop.table(table(vivenda$V5))